# Generated by Django 2.2.5 on 2020-01-17 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='rem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rem_name', models.CharField(max_length=256, unique=True)),
                ('rem_on', models.DateTimeField()),
            ],
        ),
    ]
